In [2]:
import numpy as np

# <center> TP2 - Chiffrement par substitution polyalphabétique </center>
<center> 2024/2025 - L. Naert, T. Ferragut, T. Godin </center>

_Certains exemples et textes de ce TP sont tirés de Exercices et Problèmes de cryptographie de Damien Vergnaud, 3ème édition_

Dans le chiffrement par substitution monoalphabétique, un symbole du message en clair était toujours remplacé par un même symbole pour constituer le message chiffré et un symbole du chiffré correspondait toujours au même symbole du clair. L'attaque par analyse de fréquence est donc très efficace sur ce type de chiffrement. 

Dans le chiffrement par substitution polyalphabétique, plusieurs alphabets de chiffrement sont utilisés. Un symbole du message en clair sera remplacé par un autre symbole en fonction de sa position dans le clair, de l'algorithme de chiffrement utilisé et de la clef choisi. Ainsi, deux occurences d'un même symbole dans le clair peuvent être remplacées par des symboles différents dans le chiffré. Et un même symbole dans le chiffré peut servir à coder des lettres différentes du clair. 

Dans ce TP, nous étudierons 2 types de chiffrement par substitution polyalphabétique : le chiffrement de Vigenère et le chiffrement de Hill.

Pour chaque type de chiffrement, nous développerons des fonctions pour:
1. chiffrer un message en clair à l'aide d'une clef
2. déchiffrer un message (en connaissant la clef)
3. (décrypter un message (ne connaissant pas la clef)) $\to$ partie optionnelle


Par convention, nous appellerons :
- $k$ : la clef
- $E_k$ : la fonction de chiffrement
- $D_k$ : la fonction de déchiffrement
- $m$ : le message en clair
- $m_i$ : la lettre de rang $i$ sur message en clair
- $c$ : le message chiffré
- $c_i$ : la lettre de rang $i$ sur message chiffré



## 1 - Chiffrement de Vigenère

Le chiffrement de Vigenère consiste à effectuer de façon périodique plusieurs chiffrements par décalage. La clef utilisée est un mot, bien plus court que le message à chiffrer, qui donne la valeur du décalage à effectuer pour chaque lettre du clair.

Par exemple, chiffrons le mot __chiffrement__ à l'aide de l'algorithme de Vigenère et de la clef __clef__. Cette clef indique que :
- la première lettre du clair sera chiffrée à l'aide d'un décalage de 2 positions ('c' est codé par "2" dans $\mathbb{Z}/26\mathbb{Z}$), 
- la deuxième lettre subira un décalage de 11 positions ('l' est codé par "11"), 
- la troisième de 4 positions ('e' est codé par "4"), 
- la quatrième de 5 positions (f est codé par "5"), 
- et on recommence : la cinquième de 2 positions,
- la sixième de 11 positions
- etc.

Le mot __chiffrement__ sera donc chiffré __esmkhcirgyx__. On peut remarquer que les deux "f" du clair sont chiffrés par "k" et "h" respectivement. 

In [3]:
# Quelques fonctions utiles (ou pas)
def lettreToEntier(lettre, alphabet = "abcdefghijklmnopqrstuvwxyz"):
    return alphabet.find(lettre)
def entierToLettre(a, alphabet = "abcdefghijklmnopqrstuvwxyz"):
    return alphabet[int(a)]

print("Lettre -> entier : w ->", lettreToEntier('w'))
print("Entier -> Lettre : 22 ->", entierToLettre(22))

Lettre -> entier : w -> 22
Entier -> Lettre : 22 -> w


### 1 - a) Chiffrement


> __Question 1 (chiffrement)__ : Définir une fonction `chiffrementVigenere(msgClair, clef, alphabet)` qui étant donné un message en clair `msgClair`, un mot `clef` et un alphabet `alphabet` (par défaut, l'alphabet français) renvoie le message chiffré par l'algorithme de Vigenère.

_Note_ : il est bien sûr possible et conseillé de réutiliser les fonctions codées dans le TP précédent.

In [4]:
def chiffrementVigenere(msgClair, clef, alphabet="abcdefghijklmnopqrstuvwxyz"):
    listeNouveauxCaractere = []

    for i in range (len(msgClair)):
        entierMessage = lettreToEntier(msgClair[i])
        entierClef = lettreToEntier(clef[i%len(clef)])

        nouveauEntier = entierMessage+entierClef
        listeNouveauxCaractere.append(entierToLettre(nouveauEntier%26, alphabet))

    msgChiffre = ''.join(listeNouveauxCaractere)

    #print("msgClair : " + msgClair + "\nmsgChiffre : " + msgChiffre)
    return(msgChiffre)

print(chiffrementVigenere("voicimonmessage","cesar"))


try:
    assert chiffrementVigenere("vigenere","truc") == "ozaggvlg"
    assert chiffrementVigenere("chiffrement","clef") == "esmkhcirgyx"
    print("chiffrementVigenere : OK")
except:
    print("chiffrementVigenere : ERREUR")


xsaczosfmvuwsgv
chiffrementVigenere : OK


### 1 - b) Déchiffrement

Partant du message chiffré et connaissant la clef de chiffrement, il est possible de déchiffrer le message en opérant le décalage inverse.

> __Question 2 (déchiffrement)__ : Définir une fonction `dechiffrementVigenere(msgChiffre, clef, alphabet)` qui étant donné un message chiffré `msgChiffre`, la clef qui a servi à construire ce message chiffré `clef` et un alphabet `alphabet` (par défaut, l'alphabet français) renvoie le message en clair correspondant.

In [5]:
def dechiffrementVigenere(msgChiffre, clef, alphabet="abcdefghijklmnopqrstuvwxyz"):
    listeNouveauxCaractere = []

    for i in range (len(msgChiffre)):
        entierMessage = lettreToEntier(msgChiffre[i])
        entierClef = lettreToEntier(clef[i%len(clef)])

        nouveauEntier = entierMessage-entierClef
        listeNouveauxCaractere.append(entierToLettre(nouveauEntier%26, alphabet))

    msgClair = ''.join(listeNouveauxCaractere)

    #print("msgClair : " + msgClair + "\nmsgChiffre : " + msgChiffre)
    return(msgClair)

try:
    assert dechiffrementVigenere("esmkhcirgyx","clef") == "chiffrement"
    assert dechiffrementVigenere("ozaggvlg","truc") == "vigenere"
    print("dechiffrementVigenere : OK")
except:
    print("dechiffrementVigenere : ERREUR")
    
  

dechiffrementVigenere : OK


### 1 - c) Attaque : taille de la clef et analyse de fréquence

Une attaque directe par analyse de fréquence sur l'ensemble du chiffré ne sera pas efficace sur un message chiffré avec l'algorithme de  Vigenère car une même lettre du clair peut-être chiffrée par des lettres différentes et une même lettre du chiffré peut représenter des lettres du clair distinctes.

Mais, si l'on connait le nombre de lettres $m$ que comporte la clef, il devient possible d'effectuer des analyses de fréquences efficaces sur chacun des sous-messages chiffrés déterminés en prenant les lettres du message clair espacées de $m$. Il y a donc $m$ sous-messages chiffrés à cryptanalyser par analyse de fréquence.

L'attaque pour décrypter un message codé avec Vigenère consiste donc à :
1) déterminer la taille de la clef
2) effectuer une attaque similaire à celle du chiffrement par décalage (analyse de fréquence) sur chaque sous message chiffré.

__Exemple__ : Si le chiffré est :"dbsndqufgdi" et que la clef est de longueur $3$. Il faudra faire 3 analyses de fréquences (il s'agit d'un exemple totalement fictif, le message est trop court pour pouvoir faire une analyse de fréquence, encore moins 3...) : 
- la première sur "dnud"
- la deuxième sur "bdfi"
- la troisière sur "sqg"

Il existe 2 grandes façons de déterminer la taille de la clef de chiffrement : le test de Kasiski et l'utilisation de l'indice de coïncidence. 

- Le [_test de Kasiski_](https://fr.wikipedia.org/wiki/Cryptanalyse_du_chiffre_de_Vigen%C3%A8re) repose sur le fait que si plusieurs groupes de lettres sont égaux dans le chiffré, ils correspondent certainement au même groupe de lettre dans le clair chiffré avec la même partie de la clef. La taille de l'intervalle séparant les motifs identiques sera donc probablement un multiple de la taille de la clef. S'il y a plusieurs répétitions de motifs, le plus grand diviseur commun de ces longeurs d'intervalle est possiblement la taille de la clef.

- L'[_indice de coïncidence_](https://fr.wikipedia.org/wiki/Indice_de_co%C3%AFncidence) est la probabilité que deux lettres choisies aléatoirement dans un texte soient identiques. L'indice de coïncidence permet de déterminer si un message a été chiffré par une technique de chiffrement monoalphabétique ou polyalphabétique et donne une indication sur la longueur probable de la clef dans le cas d'un chiffrement polyalphabétique.

Dans la suite, nous utiliserons l'indice de coïncidence. Détaillons cette technique.

La probabilité de tirer 2 fois la lettre $A$ est égale à : $\frac {n_A}{n}\times\frac {n_A-1}{n-1}$ avec $n_A$ le nombre de $A$ dans le message et $n$ le nombre total de lettres dans le message. 

Ainsi, la probabilité que deux lettres choisies aléatoirement dans un texte soient identiques est la somme de cette probabilité pour chaque lettre. On peut donc écrire l'indice de coïncidence ainsi :

\begin{equation}
\tag{1}
IC=\sum _{q=A}^{q=Z}{\frac {n_{q}(n_{q}-1)}{n(n-1)}}
\end{equation}

Avec $n_{q}$ pour $q \in \{A,B,C,...,Z\}$ respectivement le nombre de $A$, $B$, $C$, ..., $Z$ dans le message. 

Cette indice de coïncidence vaut environ $0.0746$ en français. __La valeur sera similaire dans un texte chiffré par substitution monoalphabétique.__ Dans le cas de lettres uniformément distribuées, l'IC vaut $0.0385$.

Dans le cas d'un chiffrement polyalphabétique pour lequel on ne connait pas le nombre d'alphabets utilisés (donc la longueur de la clef), l'indice de coïncidence se calcule de la façon suivante :

\begin{equation}
\tag{2}
IC(m)=\frac{(n-m)\times IC_{langue} + n(m-1) \times IC_{uniforme}}{m(n-1)}
\end{equation}


Avec $n$ le nombre total de lettres dans le message, $m$ la longueur de la clef, $IC_{langue}$ l'indice de coïncidence de la langue du message ($IC_{francais} = 0.0746$) et $IC_{uniforme} = 0.0385$. 

__L'objectif est de trouver la valeur de $m$ de façon à ce que $IC(m)$ (formule (2)) soit le plus proche possible de l'$IC$ (formule (1)) du message chiffré.__

_Explication de la formule :_
Partant de l'hypothèse qu'un texte de $n$ lettres en français est chiffré par le chiffre de Vigenère avec une clef de $m$ lettres ($m << n$), on souhaite calculer l'indice de coïncidence théorique de ce texte. Dans le chiffré, les paires de lettres prises au hasard peuvent être de deux types distincts : 

- Soit elles sont codées avec la même lettre de la clef (i.e. avec le même alphabet). Il y a $\frac{n \times (\frac{n}{m}-1)}{2}$ paires de ce type. Dans ce cas, la probabilité qu'il s'agisse de la même lettre devrait être proche de l'indice de coïncidence du français. 
- Soit elles sont codées avec deux lettres différentes de la clef (i.e. avec deux alphabets différents). Il y a  $\frac{n \times (n - \frac{n}{m})}{2}$ paires de ce type. Dans ce cas, la probabilité qu'il s'agisse de la même lettre devrait être proche de l'indice de coïncidence dans le cas de lettres uniformément distribuées.

Ainsi, le nombre de paires de deux lettres identiques dans un chiffré en français sera proche de :

$$\frac{n \times (\frac{n}{m}-1)}{2} \times IC_{francais} + \frac{n \times (n - \frac{n}{m})}{2} \times IC_{uniforme}$$

En divisant cette expression par le nombre total de paires de lettre dans le message ($\frac{n(n-1)}{2}$), on obtient : 

\begin{align*}
  IC(l) &  = \frac{2}{n(n-1)}\times (\frac{n \times (\frac{n}{m}-1)}{2} \times IC_{francais} + \frac{n \times (n - \frac{n}{m})}{2} \times IC_{uniforme})\\
        & = \frac{1}{(n-1)} \times ((\frac{n}{m}-1) \times IC_{francais} + (n - \frac{n}{m}) \times IC_{uniforme})\\
        & = \frac{n-m}{m(n-1)} \times IC_{francais}+ \frac {n(m-1)}{(n-1)m} \times IC_{uniforme}\\
        &\\
        & = \frac{(n-m)\times IC_{francais} + n(m-1) \times IC_{uniforme}}{m(n-1)}
\end{align*}

> __Question 3 (indice de coincidence)__ :
> - Définir une fonction `iC(msgChiffre, alphabet)` qui étant donné un message chiffré `msgChiffre` et un alphabet `alphabet` (par défaut, l'alphabet français) renvoie l'indice de coïncidence du message (formule (1))
> - Parmi les deux messages chiffré $c1$ et $c2$ : lequel a le plus de chance d'être chiffré par substitution monoaplphabétique ? L'autre est chiffré par Vigenère.
> - Définir une fonction `iC_polyalpha(msgChiffre, k, icLangue, icUniforme, alphabet)` qui étant donné un message chiffré `msgChiffre`, une longueur de clef `m`, un alphabet `alphabet` (par défaut, l'alphabet français), l'indice de coincidence de la langue (par défaut celui du français) et l'indice de coincidence si distribution uniforme (par défaut celui pour 26 lettres), renvoie l'indice de coïncidence du message (formule (2))
> - Donner les deux tailles de clef les plus probable pour le message chiffré avec Vigenère.


In [26]:
def iC(msgChiffre, alphabet="abcdefghijklmnopqrstuvwxyz"):
    freq = {letter: 0 for letter in alphabet}
    for letter in msgChiffre:
        if letter in freq:
            freq[letter] += 1

    N = len(msgChiffre)
    numerator = sum(f * (f - 1) for f in freq.values())  # Somme des f_i(f_i - 1)
    denominator = N * (N - 1)  # N(N - 1)

    ic = numerator / denominator if denominator != 0 else 0
    return ic

    
c1 = "zbpuevpuqsdlzgllksousvpasfpddggaqwptdgptzweemqzrdjtddefekeferdprrcyndgluaowcnbptzzzrbvpssfpashpncotemhaeqrferdlrlwwertlussfikgoeuswotfdgqsyasrlnrzppdhtticfrciwurhcezrpmhtpuwiyenamrdbzyzwelzucamrptzqseqcfgdrfrhrpatsepzgfnaffisbpvdblisrplzgnemswaqoxpdseehbeeksdptdttqsdddgxurwnidbdddplncsd"
c2 = "svnhfmmvshpfdskrsfsklvorensrfkkfbnryfefsfmzhroruerbnrslrofshmrlfhonladuuerprskfuudsrfkkrskdvsdmufnkmfdhhrnsyrnorgrnmfyerpdrermrkkeronladuuersrlveerhyvsoyfhuvelrprskfmfyerpdrermrkkeronuefslfdhdorpyvnemfornwdrpr"


def iC_polyalpha(msgChiffre, m, icLangue=0.0746, icUniforme=0.0385, alphabet="abcdefghijklmnopqrstuvwxyz"):
    blocs = ['' for _ in range(m)]
    for i, letter in enumerate(msgChiffre):
        bloc_idx = i % m
        blocs[bloc_idx] += letter

    ic_poly = 0
    for bloc in blocs:
        ic_poly += iC(bloc, alphabet)

    ic_poly /= m

    return (ic_poly - icUniforme) / (icLangue - icUniforme)




print(f"Indice de coïncidence de c1 : {iC(c1)}")
print(f"Indice de coïncidence de c2 : {iC(c2)}")

for m in range(2, 15): 
    print(f"IC polyalpha pour m = {m}: {iC_polyalpha(c1, m)}")


Indice de coïncidence de c1 : 0.049219073609317515
Indice de coïncidence de c2 : 0.07701509017298491
IC polyalpha pour m = 2: 0.5270577462454487
IC polyalpha pour m = 3: 0.2849976752257651
IC polyalpha pour m = 4: 1.258254358406518
IC polyalpha pour m = 5: 0.2335729954363412
IC polyalpha pour m = 6: 0.46070818346155895
IC polyalpha pour m = 7: 0.2123891242869689
IC polyalpha pour m = 8: 1.3786788953808673
IC polyalpha pour m = 9: 0.23913065062202762
IC polyalpha pour m = 10: 0.49494324639992804
IC polyalpha pour m = 11: 0.29811216791826206
IC polyalpha pour m = 12: 1.187175865605349
IC polyalpha pour m = 13: 0.3564798042697596
IC polyalpha pour m = 14: 0.6230405852383231


> __Bonus : question 4 (attaque par analyse de fréquence avec longueur de clef connue)__ :
> 
__Attention, cette partie n'est à faire que si le reste du TP (dont Chiffrement de Hill en partie 2) est terminé.__
- Définir une fonction `attaqueFrequenceVig(msgChiffre, l, frequenceLangue, alphabet)` qui décrypte le message en paramètre en effectuant des analyses de fréquences connaissant la longueur `l` de la clef ayant servie à chiffrer le message. `frequenceLangue` est un dictionnaire des fréquences dans la langue du message (le dictionnaire des fréquences de chaque lettre en français `frequenceFrancais` vous est fourni).

_Note : n'hésitez pas à utiliser des fonctions écrites dans le TP précédent._

In [29]:
frequenceFrancais = {'a': 8.15, 'b': 0.97, 'c': 3.15, 'd': 3.73, 'e': 17.39, 
                     'f': 1.12, 'g': 0.97, 'h': 0.85, 'i': 7.31, 'j': 0.45, 
                     'k': 0.02, 'l': 5.69, 'm': 2.87, 'n': 7.12, 'o': 5.28, 
                     'p': 2.80, 'q': 1.21, 'r': 6.64, 's': 8.14, 't': 7.22, 
                     'u': 6.38, 'v': 1.64, 'w': 0.03, 'x': 0.41, 'y': 0.28, 
                     'z': 0.15}


def attaqueFrequenceVig(msgChiffre, l, frequenceLangue = frequenceFrancais, alphabet="abcdefghijklmnopqrstuvwxyz"):
    return "TODO"

c = "zbpuevpuqsdlzgllksousvpasfpddggaqwptdgptzweemqzrdjtddefekeferdprrcyndgluaowcnbptzzzrbvpssfpashpncotemhaeqrferdlrlwwertlussfikgoeuswotfdgqsyasrlnrzppdhtticfrciwurhcezrpmhtpuwiyenamrdbzyzwelzucamrptzqseqcfgdrfrhrpatsepzgfnaffisbpvdblisrplzgnemswaqoxpdseehbeeksdptdttqsdddgxurwnidbdddplncsd"

try:
    assert attaqueFrequenceVig(c,4) == "aneufheureslasalledutheatredesvarietesetaitencorevidequelquespersonnesaubalconetalorchestreattendaientperduesparmilesfauteuilsdeveloursgrenatdanslepetitjourdulustreademifeuxuneombrenoyaitlagrandetacherougedurideauetpasunbruitnevenaitdelascenelarampeeteintelespupitresdesmusiciensdebandes"
    print("attaqueFrequenceVig : OK")
except:
    print("attaqueFrequenceVig : ERREUR")

attaqueFrequenceVig : ERREUR


## 2 - Chiffrement de Hill

Le chiffrement de Hill est un type de chiffrement par substitution polyalphabétique où les lettres du clair sont chiffrées et déchiffrées par paquets et non les unes à la suite des autres. Ce chiffrement est donc mieux protégé contre les attaques par analyse de fréquence.

Pour chiffrer, on commence par choisir une matrice carrée inversible (nous verrons plus tard comment vérifier qu'une matrice est inversible dans $\mathbb{Z}/26\mathbb{Z}$) de taille $p \times p$. Cette matrice constitue la clef de chiffrement. Ensuite, le message en clair est divisé en blocs/vecteurs de longueur $p$. Le dernier bloc est éventuellement complété avec une lettre choisie arbitrairement si sa longueur est différente de $p$. Chaque vecteur est chiffré en le multipliant avec la matrice carré. Evidemment, pour effectuer la multiplication matricielle, les lettres des messages sont converties en nombre entre 0 et 25. 

La fonction de chiffrement correspondante pour un bloc de $p$ lettres est : 

\begin{align*}
  E \colon (\mathbb{Z}/26\mathbb{Z})^p &\to (\mathbb{Z}/26\mathbb{Z})^p\\
    \begin{pmatrix}
m_i\\
m_{i+1}\\
... \\
m_{i+p-1} \\
\end{pmatrix} & \mapsto \begin{pmatrix}
c_i\\
c_{i+1}\\
... \\
c_{i+p-1} \\
\end{pmatrix} = K \times     \begin{pmatrix}
m_i\\
m_{i+1}\\
... \\
m_{i+p-1} \\
\end{pmatrix}
\end{align*}

où $K$ est une matrice carrée inversible de taille $p \times p$.

Par exemple, Chiffrons le message "TEXTE" avec une matrice $K \in \mathcal{M_{2,2}}$ : 
$\begin{pmatrix}
3 & 5\\
6 & 17\\
\end{pmatrix}$.

Nous commençons par faire des blocs de 2 lettres : "TE","XT","EW" (ici, on rajoute un W en fin de message pour avoir un dernier bloc de deux lettres car le message initial n'a pas un nombre pair de lettres). 

"TE" correspond au couple de valeurs (19,4). 


$
\begin{pmatrix}
3 & 5\\
6 & 17\\
\end{pmatrix} \times
\begin{pmatrix}
19\\
4\\
\end{pmatrix} = 
\begin{pmatrix}
77\\
182\\
\end{pmatrix}
$


Il faut ensuite convertir le résultat $\begin{pmatrix}
77\\
182\\
\end{pmatrix}$ en nombre de $\mathbb{Z}/26\mathbb{Z}$ :$\begin{pmatrix}
25\\
0\\
\end{pmatrix}$ puis en lettre : $\begin{pmatrix}
Z\\
A\\
\end{pmatrix}.$
"TE" sera donc chiffré "ZA". 
En recommançant le processus pour les autres couples de lettres, le clair "TEXTE" devient le chiffré "ZAITSI".

### 2 - a) Chiffrement

> __Question 5 (chiffrement)__ : Définir une fonction `chiffrementHill(msgClair, clef, lettreRemplacement, alphabet)` qui étant donné un message en clair `msgClair`, une clef de chiffrement `clef` sous forme de matrice carré $p \times p$ (np.array), une lettre de "padding" (par défaut "w") s'il n'est pas possible de diviser le message clair en blocs de taille p et un alphabet `alphabet` (par défaut, l'alphabet français), renvoie le message chiffré correspondant.

_Remarque : voir le try/assert pour avoir le format des entrées._

In [11]:
def chiffrementHill(msgClair, clef, lettrePadding='w', alphabet="abcdefghijklmnopqrstuvwxyz"):
    taille_clef = clef.shape[0]
    
    while len(msgClair) % taille_clef != 0:
        msgClair += lettrePadding
    
    def lettre_to_index(lettre):
        return alphabet.index(lettre)
    
    def index_to_lettre(index):
        return alphabet[index % len(alphabet)]
    
    msgClairIndices = [lettre_to_index(c) for c in msgClair]
    
    blocs = [msgClairIndices[i:i+taille_clef] for i in range(0, len(msgClairIndices), taille_clef)]
    
    msgChiffre = []
    for bloc in blocs:
        vecteur_bloc = np.array(bloc).reshape((taille_clef, 1))
        bloc_chiffre = np.dot(clef, vecteur_bloc) % len(alphabet)
        msgChiffre.extend(bloc_chiffre.flatten())
    
    msgChiffreLettres = ''.join(index_to_lettre(i) for i in msgChiffre)
    return msgChiffreLettres

    
try:
    assert chiffrementHill("texte",np.array([[3,5],[6,17]])) == "zaitsi"
    assert chiffrementHill("chiffredehill",np.array([[1,3,1],[1,1,0],[2,9,3]])) == "fjnlkcrhvqppvha"
    print("chiffrementHill : OK")
except:
    print("chiffrementHill : ERREUR")


chiffrementHill : OK


### 2 - b) Déchiffrement


Partant du message chiffré $c$ et connaissant la matrice de chiffrement de taille $p \times p $, il est possible de déchiffrer le message pour obtenir le clair $m$.

Il s'agit de diviser le message chiffré en vecteurs de $p$ lettres et de multiplier ces vecteurs par l'__inverse__ de la matrice de chiffrement.

La fonction de déchiffrement d'un bloc de $p$ lettres est ainsi : 

\begin{align*}
  D \colon (\mathbb{Z}/26\mathbb{Z})^p &\to (\mathbb{Z}/26\mathbb{Z})^p\\
    \begin{pmatrix}
c_i\\
c_{i+1}\\
... \\
c_{i+p-1} \\
\end{pmatrix} & \mapsto \begin{pmatrix}
m_i\\
m_{i+1}\\
... \\
m_{i+p-1} \\
\end{pmatrix} = K^{-1} \times     \begin{pmatrix}
c_i\\
c_{i+1}\\
... \\
c_{i+p-1} \\
\end{pmatrix}
\end{align*}

où $ K^{-1}$ est l'inverse de la matrice de chiffrement K dans $\mathbb{Z}/26\mathbb{Z}$.


Pour déchiffrer le message, nous avons donc besoin d'inverser la matrice K dans $\mathbb{Z}/26\mathbb{Z}$. 


__La matrice K est inversible dans $\mathbb{Z}/n\mathbb{Z}$ si son déterminant est inversible dans $\mathbb{Z}/n\mathbb{Z}$.__





> __Question 6 :__
- Faire une fonction `estInversibleMat(k, n)` qui renvoie `True` si la matrice carrée $k$ (de type np.array) est inversible sur $\mathbb{Z}/n\mathbb{Z}$ et `False`sinon.

_Note : vous pouvez utiliser `np.linalg.det(mat)` pour obtenir le déterminant de `mat`. Attention python renvoie parfois un nombre décimal pour ce déterminant. Il faut donc arrondir le résultat (`np.round(x)`)_

In [14]:
def estInversibleMat(k,n):
    det = int(np.round(np.linalg.det(k))) % n
    
    if det == 0:
        return False
    
    try:
        inv = pow(det, -1, n)
        return True
    except ValueError:
        return False

try:
    assert estInversibleMat(np.array([[3,5],[6,17]]),26) == True
    assert estInversibleMat(np.array([[1,3,1],[1,1,0],[2,9,3]]),26) == True
    assert estInversibleMat(np.array([[1,2],[3,4]]),26) == False
    print("estInversibleMat : OK")
except:
    print("estInversibleMat : ERREUR")


estInversibleMat : OK


__Pour inverser K, il faut multiplier la transposée de la comatrice (= matrice des cofacteurs) de K par un inverse modulaire de son déterminant.__


> __Question 7 (comatrice) :__
> La fonction `reductionMatrice(mat,rowNum,colNum)` renvoie la matrice donnée en paramètre (sous forme de np.array) à laquelle on a retiré la ligne `rowNum` et la colonne `colNum`. En utilisant cette fonction, écrire la fonction `comatrice(mat)` qui renvoie la matrice des cofacteurs de `mat`. 

In [15]:
def reductionMatrice(mat,rowNum,colNum):
    n, m = mat.shape
    if(rowNum == 0 ) :
        B = mat[rowNum+1:]
    elif (rowNum == n-1) :
        B = mat[:rowNum]
    else :
        B = np.concatenate((mat[:rowNum],mat[rowNum+1:]))


    if(colNum == 0 ) :
        cofacteur = B[:,colNum+1:]
    elif (colNum == m-1) :
        cofacteur = B[:,:colNum]
    else :
        cofacteur = np.concatenate((B[:,:colNum],B[:,colNum+1:]))
        
    cofacteur = np.reshape(cofacteur, (n-1,m-1))
    return cofacteur

A = np.array([[1, 2, 3], [4, 5,6],[7,8,9]])
print(A)
print("Matrice A après retrait de la ligne 2 et colonne 1 :\n", reductionMatrice(A, 2,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrice A après retrait de la ligne 2 et colonne 1 :
 [[1 4]
 [3 6]]


In [17]:
def comatrice(mat):
    n, m = mat.shape
    comat = np.zeros((n, n))
    
    for i in range(n):
        for j in range(n):
            minor = reductionMatrice(mat, i, j)
            cofacteur = (-1) ** (i + j) * int(np.round(np.linalg.det(minor)))
            comat[i, j] = cofacteur
    
    return comat

try:
    A = np.array([[1, 2, 3], [4, 5,6],[7,8,9]])
    assert (comatrice(A) ==  np.array([[-3,6,-3], [6,-12,6], [-3,6,-3]])).all()
    print("comatrice : OK")
except:
    print("comatrice : ERREUR")

comatrice : OK


> __Question 8 (matrice inverse) :__
> A partir de la fonction précédente, faire une fonction `inverseMat(k, n)` qui teste si la matrice k (de type np.array) est inversible. Si oui, renvoie la matrice inverse de k dans $\mathbb{Z}/n\mathbb{Z}$ et sinon, renvoie -1. N'hésitez pas à réutiliser des fonctions du TP précédent.

In [22]:
def inverseMat(k,n):
    det = round(np.linalg.det(k))
    det_inv = pow(int(det) % n, -1, n)

    comatrice = np.zeros(k.shape)
    for i in range(k.shape[0]):
        for j in range(k.shape[1]):
            minor = np.delete(np.delete(k, i, axis=0), j, axis=1)
            comatrice[i, j] = ((-1)**(i+j)) * round(np.linalg.det(minor))

    k_inv = (det_inv * comatrice.T) % n  
    return k_inv.astype(int)

try:
    assert (inverseMat(np.array([[3,5],[6,17]]),26) == np.array([[7, 1],[22, 15]])).all()
    assert (inverseMat(np.array([[9,4],[5,7]]),26) == np.array([[ 5, 12],[15, 25]])).all()
    assert (inverseMat(np.array([[3,7],[5,8]]),26) == np.array([[ 4, 3],[17, 21]])).all()
    assert (inverseMat(np.array([[1,3,1],[1,1,0],[2,9,3]]),26) == np.array([[ 3,0,25],[23,1,1],[ 7,23,24]])).all()
    print("inverseMat : OK")
except:
    print("inverseMat : ERREUR")

inverseMat : OK


> __Question 9 (déchiffrement)__ : Définir une fonction `dechiffrementHill(msgChiffre, clef, alphabet)` qui étant donné un message chiffré `msgChiffre`, la matrice de chiffrement `clef` qui a servi à construire ce message chiffré et un alphabet `alphabet` (par défaut, l'alphabet français) renvoie le message en clair correspondant.

In [24]:
def dechiffrementHill(msgChiffre, clef, alphabet = "abcdefghijklmnopqrstuvwxyz"):
    n = len(alphabet)
    taille_bloc = clef.shape[0]  

    clef_inv = inverseMat(clef, n)
    if type(clef_inv) == int and clef_inv == -1:
        raise ValueError("La matrice de chiffrement n'est pas inversible dans Z/nZ")

    print("Matrice clef :\n", clef)
    print("Matrice inverse :\n", clef_inv)

    indices_chiffres = [alphabet.index(c) for c in msgChiffre]
    print("Indices du message chiffré :", indices_chiffres)

    msg_clair_indices = []
    for i in range(0, len(indices_chiffres), taille_bloc):
        bloc = np.array(indices_chiffres[i:i+taille_bloc])
        if len(bloc) != taille_bloc:
            raise ValueError("Le message n'est pas divisible en blocs de la taille requise")
        bloc = bloc.reshape((taille_bloc, 1))  
        bloc_dechiffre = (clef_inv @ bloc) % n  
        msg_clair_indices.extend(bloc_dechiffre.flatten())  

    msgClair = ''.join([alphabet[idx % n] for idx in msg_clair_indices])
    return msgClair


try:
    assert dechiffrementHill("zaitsi",np.array([[3,5],[6,17]])) == "textew"
    assert dechiffrementHill("fjnlkcrhvqppvha",np.array([[1,3,1],[1,1,0],[2,9,3]])) == "chiffredehillww"
    print("dechiffrementHill : OK")
except:
    print("dechiffrementHill : ERREUR")

Matrice clef :
 [[ 3  5]
 [ 6 17]]
Matrice inverse :
 [[ 7  1]
 [22 15]]
Indices du message chiffré : [25, 0, 8, 19, 18, 8]
Matrice clef :
 [[1 3 1]
 [1 1 0]
 [2 9 3]]
Matrice inverse :
 [[ 3  0 25]
 [23  1  1]
 [ 7 23 24]]
Indices du message chiffré : [5, 9, 13, 11, 10, 2, 17, 7, 21, 16, 15, 15, 21, 7, 0]
dechiffrementHill : OK
